---
title: "Pre- v.s. Post-yard Comparison of Water Chemistry"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, echo=FALSE, results='asis'}
f <- read.csv(file = "C:/Users/sgm/Google Drive/Caspar Creek_sgm/caspar/output/tb/tb_wide.csv")
View(f)
vars <- c('ec','ph','turb','tn','nh4n','no3n','tp','po4','doc')
post <- c("","_avg","_avg_grams","_avg_kg","_avg_ha")

#hax
f[,unlist(lapply(post[3:5], function(p) paste0(vars[1:3], p)))] <- NA


res <- lapply(split(f, f$subws_name), function(g) {
  cat(paste0("## ", g$subws_name[1], "\n"))
  lapply(split(g, g$season), function(h) {
    cat(paste0("## ", h$season[1]), "\n")
    i <- as.list(1:length(post))
    n <- lapply(i, function(j) {
      k <- paste0(vars, post[[j]])
      if(nrow(h) > 3) {
        n <- 1
        tt <- list()
        l <- apply(h[,k], 2, FUN = function(m) {
          m.pre <- m[h$period_name == "pre_yard"]
          m.post <- m[h$period_name == "post_yard"]
          if(length(na.omit(m.pre)) > 1 & 
             length(na.omit(m.post)) > 1) {
            
          df <- rbind(data.frame(period="pre_yard", value=m.pre),
                data.frame(period="post_yard", value=m.post))
          
          a <- aov(data=df, value ~ period)
          tt <- TukeyHSD(a)
          pval <- summary(a)[[1]][["Pr(>F)"]]
          
              #(t.test(m.pre, m.post, alternative = "two.sided", var.equal = FALSE))
            # 
          if(pval[1] < 0.05)
            print(paste0(h$subws_name[1], " ", h$season[1], " ", k[n]))
            
          }
          n <<- n+1 # warning: double assignment
          return(tt)
          })
      }})
    
    names(n) <- c("raw","roll","grams","kilos","area")
    return(n)
  })
})

# reject null hypothesis if p-value greater than/equal to alpha (aka significance level) 
# alpha/significance level 0.05 = confidence level 0.95 (default t.test argument)

names(res)

unfuckerate <- function(l) {
  if(typeof(l) == 'list') {
    foo <-  lapply(l, unfuckerate)
    l.c <- unlist(lapply(foo, nrow))
    l.n <- character(0)
    l.names <- names(l)
    for(n in 1:length(l.names)) {
      if(length(l.c[n]))
        l.n <- c(l.n, rep(l.names[n], l.c[n]))
    }
    l.r <- as.data.frame(do.call('rbind', foo))
    if(length(l.n) & length(l.r) & !is.null(l.r))
      if(nrow(l.r) == length(l.n)) {
         l.r <- cbind(l.r, l.n)
      }
    return(l.r)
  } 
  return(l)
}
uf <- unfuckerate(res)
```
